# Liste combinée demots médicaux
mots_medicaux_raw = [
    "douleur", "poitrine", "mal", "gêne", "souffrance", "oppression", "serrement", "poids",
    "essoufflement", "respirer", "respiration", "souffle", "court", "difficile",
    "sueur", "transpiration", "moiteur", "suer",
    "vertige", "étourdissement", "tête", "tourner",
    "fatigue", "épuisement", "lassitude", "faiblesse", "abattement",
    "pâle", "pâleur", "blême",
    "angoisse", "anxiété", "peur", "crainte", "panique", "stress",
    "palpitation", "battement", "coeur", "rapide", "fort",
    "ischémie", "obstruction", "blocage", "rétrécissement", "artère",
    "rupture", "déchirure", "plaque", "athérome",
    "caillot", "thrombus", "thrombose", "embolie",
    "tabac", "cigarette", "fumer", "fumeur",
    "diabète", "sucre", "glycémie",
    "hypertension", "tension", "élevée",
    "cholestérol", "graisse", "lipide",
    "obésité", "poids", "surpoids", "obèse", "gros",
    "sédentaire", "inactivité", "bouger",
    "alcool", "boisson", "boire",
    "antécédent", "passé", "historique", "familial",
    "infarctus", "crise", "cardiaque", "myocarde", "attaque",
    "avc", "cérébral", "vasculaire", "accident",
    "serre", "étau", "constriction",
    "rétrosternal", "sternum", "derrière",
    "gauche", "droit", "bras", "mâchoire", "cou", "dos", "épaule",
    "thoracique", "thorax",
    "malaise", "évanouissement", "syncope", "perte", "connaissance",
    "sensation", "impression",
    "compression", "pression",
    "chaleur", "brûlure", "feu", "brûlant",
    "détresse", "urgence", "vital",
    "trouble", "difficulté", "problème",
    "inconfort",
    "halètement", "rapide",
    "nécrose", "mort", "cellule", "tissu",
    "arythmie", "rythme", "irrégulier",
    "tachycardie", "bradycardie", "lent",
    "asystolie", "arrêt",
    "bloc", "conduction",
    "coronaire", "coronaropathie",
    "stent", "ressort", "angioplastie", "dilatation",
    "diastolique", "systolique",
    "cathéter", "sonde",
    "dysfonction", "ventricule", "ventriculaire",
    "fibrillation", "auriculaire",
    "myocardite", "péricardite", "inflammation",
    "cyanose", "bleu", "lèvre", "doigt",
    "œdème", "gonflement", "eau", "rétention", "cheville", "jambe",
    "hypoxie", "oxygène", "manque",
    "hypotension", "basse",
    "régurgitation", "fuite", "valve", "valvulaire", "valvulopathie",
    "dyspnée", "apnée", "tachypnée", "hypopnée", "hyperventilation",
    "hypoxémie", "anoxie",
    "hémorragie", "saignement", "perte", "sang",
    "bruit", "souffle", "anormal",
    "échocardiographie", "écho", "ultrason",
    "saturation", "oxymètre",
    "vasodilatation", "vasoconstriction", "vaisseau",
    "angiographie", "radio",
    "allergie", "réaction",
    "analgésique", "antidouleur", "calmant", "médicament",
    "anesthésie", "endormir", "local", "général",
    "antibiotique", "infection", "bactérie",
    "antipyrétique", "fièvre",
    "antiseptique", "désinfectant",
    "asphyxie", "étouffement",
    "biopsie", "prélèvement", "analyse",
    "bronche", "bronchite", "poumon",
    "carcinome", "cancer", "tumeur",
    "carotide",
    "céphalée", "tête",
    "chirurgie", "opération", "opérer",
    "circulation", "sanguin",
    "coma", "inconscient",
    "contusion", "bleu", "coup", "choc",
    "coupure", "plaie", "blessure",
    "crâne",
    "démence", "mémoire", "confusion",
    "dérèglement", "déséquilibre",
    "déshydratation", "soif", "sec",
    "diarrhée", "selle", "liquide",
    "dorsalgie", "dos",
    "endocrine", "hormone", "glande",
    "épilepsie", "convulsion",
    "épistaxis", "nez",
    "érythème", "rougeur", "peau",
    "exsudat", "suintement",
    "fracture", "cassé", "os",
    "gastro", "entérite", "estomac", "intestin", "vomir", "nausée",
    "hématome",
    "hémoptysie", "cracher",
    "hépatite", "foie",
    "hernie","gaz", "carbonique", "co2",
    "hyperthermie", "hypothermie", "température", "chaud", "froid", "jaunisse", "jaune",
    "injection", "piqûre",
    "insuffisance", "déficience", "faillir",
    "intervention",
    "intoxication", "poison",
    "intubation", "tube", "respirateur",
    "intraveineuse", "perfusion", "veine",
    "lésion", "atteinte", "dommage",
    "luxation", "déboitement",
    "méningite", "méninge",
    "migraine",
    "néoplasie",
    "nodule", "boule", "masse",
    "œsophage",
    "paralysie", "paralysé", "mouvement",
    "pathologie", "maladie",
    "phlébite",
    "phobie",
    "pneumonie", "pneumothorax",
    "ponction", "aiguille",
    "prothèse",
    "prurit", "démangeaison", "gratter",
    "psychiatrie", "mental", "psychologique",
    "radiographie",
    "réanimation", "urgence", "soin", "intensif",
    "réflexe",
    "rhume",
    "scanner", "imagerie",
    "sclérose", "durcissement",
    "sécrétion",
    "septicémie", "choc", "septique",
    "sonde",
    "spasme", "contraction", "involontaire",
    "stérile", "propre",
    "suture", "point",
    "toux", "tousser",
    "toxine",
    "traitement", "thérapie", "soigner",
    "ulcère",
    "urine", "vessie", "miction", "uriner",
    "utérus", "infarctus",
    "anémie", "fer", "globule",
    "asepsie",
    "asthénie",
    "aorte",
    "bradyarythmie",
    "cellule",
    "cirrhose",
    "colique", "ventre",
    "colonne", "vertébrale",
    "crampe", "muscle",
    "décompensation", "aggravation",
    "désaturation",
    "emphysème",
    "enflure",
    "enrouement", "voix",
    "fécalome", "constipation",
    "fistule",
    "gencive", "dent",
    "glucose",
    "hallucination", "voir", "entendre",
    "hémiplégie", "moitié", "corps",
    "hyperplasie",
    "hypersensibilité",
    "immunodéficience", "immunitaire", "défense",
    "jambes", "jambe",
    "lumbago",
    "médicament", "pilule", "comprimé", "gélule", "sirop",
    "névralgie", "nerf",
    "occlusion", "bouchon",
    "œsophagite",
    "pancréatite", "pancréas",
    "pathogène", "germe", "microbe", "virus",
    "péricarde",
    "plèvre",
    "psoriasis",
    "récidive", "revenir", "rechute",
    "rhinite",
    "rhumatisme", "articulation","raideur",
    "thermomètre",

    "homme", "femme", "masculin", "féminin", "mari", "épouse", "conjoint", "parent", "enfant",
    "âge", "vieux", "jeune", "adulte", "bébé", "nourrisson",
    "médecin", "docteur", "infirmière", "infirmier", "soignant", "urgentiste", "cardiologue", "spécialiste", "généraliste", "samu", "pompier",
    "symptôme", "signe",
    "palpation", "toucher", "sentir",
    "percussion", "taper",
    "inspection", "regarder", "observer",
    "constant", "intermittent", "continu", "parfois", "souvent", "jamais", "toujours",
    "aigu", "chronique", "soudain", "progressif", "brutal", "insidieux",
    "intense", "sévère", "modéré", "léger", "faible", "fort", "insupportable",
    "irradier", "irradiation", "diffuser", "étendre",
    "augmenter", "diminuer", "aggraver", "soulager", "calmer",
    "effort", "repos", "mouvement", "marche", "escalier", "nuit", "jour", "matin", "soir",
    "allongé", "assis", "debout", "couché",
    "nauséeux", "envie",
    "froid", "chaud", "frisson", "grelotter",
    "sommeil", "dormir", "insomnie", "réveil",
    "appétit", "manger", "boire", "faim", "soif",
    "humeur", "moral", "triste", "déprimé", "irritable",
    "normal", "anormal", "pathologique",
    "sang", "sanguin", "veineux", "artériel",
    "régime", "alimentation", "sel", "sucre", "gras",
    "exercice", "sport", "activité", "physique",
    "conscient", "lucide", "orienté", "désorienté",
    "peau", "muqueuse",
    "visage", "oeil", "oreille", "bouche", "langue", "gorge",
    "membre", "supérieur", "inférieur",
    "abdomen", "ventre",
    "articulation",
    "nerveux", "nerveuse",
    "musculaire", "muscle",
    "osseux",
    "pulmonaire",
    "rénal", "rein",
    "hépatique",
    "digestif",
    "neurologique", "neuro",
    "psychique",
    "métabolique", "métabolisme",
    "génétique", "héréditaire",
    "inflammatoire",
    "infectieux",
    "allergique",
    "toxique",
    "traumatique", "trauma",
    "chronologique", "début", "fin", "durée", "fréquence",
    "localisé", "généralisé", "diffus",
    "superficiel", "profond",
    "interne", "externe",
    "positif", "négatif",
    "numération", "formule",
    "ionogramme", "sodium", "potassium", "chlore", "calcium", "magnésium",
    "créatinine", "urée",
    "ferritine",
    "vitesse", "aspirine",
    "morphine", "opiacé",
    "pacemaker",
    "greffe", "transplantation",
    "réadaptation", "kinésithérapie", "kiné",
    "sevrage", "tabagique", "alcoolique",
    "éducation", "thérapeutique", "conseil",
    "ambulance",
    "brancard", "lit", "fauteuil",
    "salle", "opération", "réveil", "soins",
    "cicatrice", "pansement",
    "fiable", "sensible", "spécifique",
    "coagulation", "saigner",
    "endothélium", "vaisseau",
    "athérosclérose", "artériosclérose",
    "anévrisme",
    "précharge", "postcharge", "débit",
    "fraction", "éjection",
    "sédatif", "calmer",
    "hypnotique",
    "anxiolytique",
    "antidépresseur",
    "vaccin", "sérum",
    "immunoglobuline",
    "corticoïde", "anti-inflammatoire", "ains",
    "spasme", "migraine", "tension",
    "confusion", "désorientation",
    "agitation", "nervosité",
    "somnolence", "léthargie",
    "tremblement",
    "convulsion",
    "ataxie", "coordination", "équilibre",
    "diplopie", "vision", "double",
    "scotome", "tache",
    "acouphène", "sifflement", "bourdonnement", "oreille", "écoulement", "déglutition", "avaler",
    "pyrosis", "acidité", "remontée",
    "éructation", "rot",
    "météorisme", "ballonnement", "gaz",
    "constipation",
    "rectorragie", "sang", "anus",
    "méléna", "noir", "fréquent",
    "cervicalgie",
    "lombalgie",
    "sciatique", "sciatalgie",
    "éruption", "cutané", "rougeur", "plaque", "bouton", "bulle", "pustule", "ulcération",
    "oedème", "gonflement",
    "adénopathie", "ganglion", "rate", "foie", "liquide", "abdomen","jaunisse",
    "ecchymose",
    "syndrome",
    "maladie",
    "affection",
    "fonctionnel",
    "organique",
    "bénin", "malin",
    "préventif", "curatif", "palliatif",
    "monitorer",
    "vital",
    "indice", "masse", "corporelle", "imc",
    "hémodynamique", "volémie",
    "pupille", "mydriase", "myosis", "isocorie", "anisocorie", "réactif",
    "photomoteur", "cornéen",
    "hydratation",
    "nutritionnel",
    "énergétique", "glucidique", "lipidique",
    "vitamine", "minéral",
    "addiction", "dépendance",
    "observance", "compliance", "traitement",
    "autonomie", "dépendance",
    "isolement", "social",
    "émotion", "émotionnel",
    "cognitif", "intellectuel",
    "moteur", "sensoriel",
    "dépistage",
    "facteur", "cause",
    "pathogénie", "mécanisme",
    "pronostic", "évolution", "chance",
    "épidémiologie", "fréquence", "incidence", "prévalence",
    "terminal", "fin",
    "rémission",
    "guérison",
    "placebo", "nocebo",
    "vulnérable", "fragile", "âgé",
    "antérieur", "postérieur", "inférieur", "supérieur", "latéral", "médial", "apical", "basal", "septal",
    "transmural", "endocardique", "épicardique",
    "mécanique",
    "rythmique",
    "ischémique",
    "hémorragique",
    "infectieuse",
    "thromboembolique",
    "pariétal",
    "libre","cohorte",
    "phase",
    "convalescence", "rétablissement", "résistant",
    "silencieux",
    "spontané", "provoqué",
    "altération", "état", "général", "dénutrition", "maigreur",
    "muscle", "perte",
    "ostéoporose", "os", "fragilité",
    "chute",
    "iatrogénie",
    "prédisposition",
    "sensibilité",
    "résistance",
    "tolérance",
    "réserve",
    "viabilité", "myocardique",
    "hibernation", "sidération",
    "remodelage", "ventriculaire",
    "dilatation", "hypertrophie",
    "pro-inflammatoire", "anti-inflammatoire",
    "oxydatif", "antioxydant",
    "gène", "expression", "régulation",
    "épigénétique",
    "microbiome", "flore", "intestinale",
    "environnement", "pollution", "bruit", "social", "économique",
    "comportement", "habitude", "vie",
    "adhésion",
    "migration",
    "prolifération",
    "apoptose", "mort", "programmée",
    "autophagie",
    "signalisation", "voie",
    "gradient", "pression", "concentration",
    "potentiel", "action", "membrane",
    "excitabilité", "conductivité", "contractilité", "automaticité",
    "couplage", "excitation-contraction",
    "énergétique", "créatine", "phosphate",
    "acide", "lactique", "lactate",
    "radical", "libre", "espèce", "réactive", "oxygène",
    "oxyde", "nitrique", "rénine","système",
    "facteur", "croissance",
    "hormone","adrénaline", "dopamine", "sérotonine", "protéine",
    "facteur",
    "interaction", "médicamenteuse",
    "toxicité", "surdosage",
]

mots_medicaux = sorted(list(set(mots_medicaux_raw)))

